packages:
  - apps/*
  - packages/*
allowBuilds:
  "@prisma/engines": true
  "@swc/core": true
  msgpackr-extract: true
  prisma: false
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - secios@1.0.2
